spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: SpringAI-demo
  ai:
    zhipuai:
      api-key: ${your_API_key}
      chat:
        options:
          model: glm-4
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis-plus:
  mapper-locations: classpath:generator/mapper/*.xml
  type-aliases-package: com.bigerboy.springaidemo.domain
